# Generated by Django 4.2.1 on 2023-06-06 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_exchanges", "0002_alter_commodity_unit_int_value"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tickers",
            new_name="Ticker",
        ),
    ]
