# Generated by Django 4.2.1 on 2023-06-12 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_exchanges", "0007_ticker_slug_alter_currency_tenor_months"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticker",
            name="slug",
        ),
    ]
