# Generated by Django 4.2.1 on 2023-06-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exchanges', '0014_commodity_commodity_descr_currency_currency_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_abbr',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_name',
            field=models.CharField(max_length=70),
        ),
    ]
