# Generated by Django 4.2.1 on 2023-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exchanges', '0019_remove_exchanges_commodities_unit_int_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='type',
            field=models.CharField(choices=[('SPOT', 'SPOT'), ('FORWARD', 'FORWARD'), ('SWAP', 'SWAP')], default='SPOT', max_length=15),
        ),
        migrations.AlterField(
            model_name='exchanges_currencies',
            name='tenor_months',
            field=models.CharField(choices=[('1 M', '1 M'), ('2 M', '2 M'), ('3 M', '3 M')], default='--', max_length=15),
        ),
    ]
