# Generated by Django 4.2.1 on 2023-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exchanges', '0023_alter_commodity_id_alter_currency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges_commodities',
            name='time_of_last_trade',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
