# Generated by Django 4.2.1 on 2023-06-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exchanges', '0024_alter_exchanges_commodities_time_of_last_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges_currencies',
            name='settlement_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exchanges_currencies',
            name='settlement_date_swap',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
